let emotes = {
  Think: "think",
  "Sit Scared": "sitscared",
  Push: "push",
  "Argue 2": "argue2",
  "Hug 2": "hug2",
  Me: "me",
  Texting: "texting",
  "Meditiate 3": "meditate3",
  "Sit 8": "sit8",
  "Wait 11": "wait11",
  "Facepalm 2": "facepalm2",
  Party: "party",
  "Idle Drunk 3": "idledrunk3",
  "Think 4": "think4",
  Hiking: "hiking",
  "Passout 5": "passout5",
  "Air Plane": "airplane",
  "Crossarms Side": "crossarmsside",
  Chill: "chill",
  "Think 3": "think3",
  Boxing: "boxing",
  "Shake Off": "shakeoff",
  "Facepalm 3": "facepalm3",
  "Fight Me": "fightme",
  Warmth: "warmth",
  "Cut Throat": "cutthroat",
  Facepalm: "facepalm",
  Curtsy: "curtsy",
  "Flip Off": "flipoff",
  "Shrug 2": "shrug2",
  "Idle 3": "idle3",
  "Finger 2": "finger2",
  "Idle 6": "idle6",
  Cloudgaze: "cloudgaze",
  Type: "type",
  Pickup: "pickup",
  Twerk: "twerk",
  Surrender: "surrender",
  "Lean Bar 4": "leanbar4",
  "Peace 2": "peace2",
  "Point Right": "pointright",
  "Lean High 2": "leanhigh2",
  "Sit Scared 3": "sitscared3",
  "Flip Off 2": "flipoff2",
  "Try Clothes 3": "tryclothes3",
  "Idle 5": "idle5",
  "Damn 2": "damn2",
  "Mind Control": "mindcontrol",
  "Jumping Jacks": "jumpingjacks",
  "Thumbs Up": "thumbsup",
  Beast: "beast",
  "Wave 8": "wave8",
  "Sit 5": "sit5",
  "Sit Chair 3": "sitchair3",
  Idle: "idle",
  Radio: "radio",
  "Clown 4": "clown4",
  "Type 2": "type2",
  "Wave 9": "wave9",
  "Sit 6": "sit6",
  Slap: "slap",
  "Screw You": "screwyou",
  Pull: "pull",
  Pushup: "pushup",
  "Lean Bar 3": "leanbar3",
  "Type 3": "type3",
  "Idle Drunk": "idledrunk",
  "Wait 2": "wait2",
  Clap: "clap",
  "Cop 2": "cop2",
  "Knuckle Crunch": "knucklecrunch",
  Point: "point",
  Meditiate: "meditate",
  "Sit Chair 4": "sitchair4",
  "Lean 3": "lean3",
  "Fight Me 2": "fightme2",
  "Nose Pick": "nosepick",
  "Idle 4": "idle4",
  "Wave 7": "wave7",
  Jog: "jog",
  Adjust: "adjust",
  Mechanic: "mechanic",
  CPR: "cpr",
  Yoga: "yoga",
  "Key Fob": "keyfob",
  "Blow Kiss": "blowkiss",
  "Idle 11": "idle11",
  "Wait 13": "wait13",
  "Passout 3": "passout3",
  "Lean Bar": "leanbar",
  Inspect: "inspect",
  "Superhero 2": "superhero2",
  Musician: "musician",
  Celebrate: "celebrate",
  "Sit Chair Side": "sitchairside",
  "Bow 2": "bow2",
  "Wait 5": "wait5",
  "Statue 2": "statue2",
  "Clap Angry": "clapangry",
  Eat: "eat",
  "Air Synth": "airsynth",
  "LOL 2": "lol2",
  "Air Guitar": "airguitar",
  Record: "record",
  "Statue 3": "statue3",
  Namaste: "namaste",
  "Wait 4": "wait4",
  "Medic 2": "medic2",
  "CPR 2": "cpr2",
  "Sit Drunk": "sitdrunk",
  "Think 2": "think2",
  Uncuff: "uncuff",
  "Lean 2": "lean2",
  "Wait 9": "wait9",
  Chicken: "chicken",
  "Fall Over 3": "fallover3",
  Countdown: "countdown",
  "Wave 2": "wave2",
  Finger: "finger",
  BBQ: "bbq",
  ATM: "atm",
  "Mechanic 2": "mechanic2",
  "Prostitue Low": "prostlow",
  "Slide 2": "slide2",
  Stumble: "stumble",
  Hammer: "hammer",
  "Wait 3": "wait3",
  "Sit 2": "sit2",
  Knock: "knock",
  Prone: "prone",
  Karate: "karate",
  Leafblower: "leafblower",
  "Crossarms 5": "crossarms5",
  "Fish Dance": "fishdance",
  "Sit 4": "sit4",
  "Stretch 4": "stretch4",
  "Wave 5": "wave5",
  Stunned: "stunned",
  "Hands Up": "handsup",
  "Idle 10": "idle10",
  Lift: "lift",
  Bartender: "bartender",
  "Mechanic 3": "mechanic3",
  "Mechanic 4": "mechanic4",
  Shrug: "shrug",
  "Slow Clap": "slowclap",
  "Jog 3": "jog3",
  Headbutt: "headbutt",
  "Facepalm 4": "facepalm4",
  Jazzhands: "jazzhands",
  OK: "ok",
  "Passout 4": "passout4",
  "Leanside 5": "leanside5",
  "Meditiate 2": "meditate2",
  "Adjust Tie": "adjusttie",
  "Nervous 3": "nervous3",
  "Fold Arms": "foldarms",
  "Boxing 2": "boxing2",
  "Thumbs Up 2": "thumbsup2",
  "Crossarms 2": "crossarms2",
  Flip: "flip",
  Bark: "bark",
  "Thumbs Up 3": "thumbsup3",
  "Cut Throat 2": "cutthroat2",
  "Karate 2": "karate2",
  "Window Shop": "windowshop",
  Janitor: "janitor",
  Weld: "weld",
  "Sunbathe Back": "sunbatheback",
  "Sunbathe 3": "sunbathe3",
  Lookout: "lookout",
  "Lapdance 3": "lapdance3",
  "Smoke Weed": "smokeweed",
  Superhero: "superhero",
  "Cop Beacon": "copbeacon",
  Smoke: "smoke",
  Pullover: "pullover",
  "Wait 10": "wait10",
  Puddle: "puddle",
  "Handshake 2": "handshake2",
  "Stick Up": "stickup",
  "Notepad 2": "notepad2",
  "Parking Meter": "parkingmeter",
  "Fall Over": "fallover",
  "Prostitue High": "prosthigh",
  "Salute 2": "salute2",
  Maid: "maid",
  "Hug 3": "hug3",
  Lean: "lean",
  Reaching: "reaching",
  Impatient: "impatient",
  Hangout: "hangout",
  Guard: "guard",
  "Sit Up": "situp",
  Hug: "hug",
  "Fall Over 2": "fallover2",
  "Lean High": "leanhigh",
  Flex: "flex",
  Bird: "bird",
  Cop: "cop",
  "Leanside 3": "leanside3",
  "Clipboard 2": "clipboard2",
  LOL: "lol",
  Chinup: "chinup",
  Metal: "metal",
  "Slide 3": "slide3",
  Scared: "scared",
  Cheer: "cheer",
  Kneel: "kneel",
  "Bum Bin": "bumbin",
  Peace: "peace",
  BOI: "boi",
  "Spider-Man": "spiderman",
  T: "t",
  "Film Shocking": "filmshocking",
  Threaten: "threaten",
  Shot: "shot",
  "Wave 6": "wave6",
  DJ: "dj",
  Stink: "stink",
  "Come at me bro": "comeatmebro",
  "Idle 7": "idle7",
  "Clown 5": "clown5",
  "Nervous 2": "nervous2",
  "Sit Sad": "sitsad",
  "Jog 5": "jog5",
  "Wait 7": "wait7",
  "Blow Kiss 2": "blowkiss2",
  "Knock 2": "knock2",
  Argue: "argue",
  Nervous: "nervous",
  "Clown 3": "clown3",
  "Wave 4": "wave4",
  "Idle Drunk 2": "idledrunk2",
  Clown: "clown",
  "Mind Control 2": "mindcontrol2",
  Drink: "drink",
  "Sunbathe 2": "sunbathe2",
  Punching: "punching",
  "Fold Arms 2": "foldarms2",
  "Stretch 2": "stretch2",
  Stretch: "stretch",
  Cough: "cough",
  Peek: "peek",
  Sleep: "sleep",
  Pee: "pee",
  Petting: "petting",
  Statue: "statue",
  "Leanside 2": "leanside2",
  "Wait 12": "wait12",
  Wait: "wait",
  "Bum Sleep": "bumsleep",
  "Scared 2": "scared2",
  "Sit Chair": "sitchair",
  "Sit 3": "sit3",
  Bow: "bow",
  "Bring It On": "bringiton",
  "Lean 5": "lean5",
  Slugger: "slugger",
  "Sit Chair 5": "sitchair5",
  Slide: "slide",
  "Mind Blown 2": "mindblown2",
  "Sit Chair 6": "sitchair6",
  Crawl: "crawl",
  "Out of Breath": "outofbreath",
  "Crossarms 3": "crossarms3",
  "Fall Over 5": "fallover5",
  "Passout 2": "passout2",
  Passout: "passout",
  "Gang Sign 2": "gangsign2",
  "Gang Sign": "gangsign",
  Yeah: "yeah",
  "Whistle 2": "whistle2",
  "Jog 2": "jog2",
  "Golf Swing": "golfswing",
  Wave: "wave",
  "Wave 3": "wave3",
  "Clown 2": "clown2",
  Sit: "sit",
  Damn: "damn",
  "Mind Blown": "mindblown",
  "Cloudgaze 2": "cloudgaze2",
  "Think 5": "think5",
  "Cop 3": "cop3",
  "T 2": "t2",
  "Point Down": "pointdown",
  "Sit Scared 2": "sitscared2",
  Rabbit: "rabbit",
  "No Way": "noway",
  "Salute 3": "salute3",
  Salute: "salute",
  Smell: "smell",
  "Slow Clap 2": "slowclap2",
  "Kneel 2": "kneel2",
  "Flip 2": "flip2",
  "Idle 2": "idle2",
  "Lean Flirt": "leanflirt",
  "Sit Chair 2": "sitchair2",
  "Try Clothes 2": "tryclothes2",
  "Wait 6": "wait6",
  Crossarms: "crossarms",
  "Sit 9": "sit9",
  "Sit 7": "sit7",
  "Type 4": "type4",
  Lapdance: "lapdance",
  Ledge: "ledge",
  Medic: "medic",
  "Push 2": "push2",
  Sunbathe: "sunbathe",
  "Jog 4": "jog4",
  "Lean 4": "lean4",
  "Leanside 4": "leanside4",
  "Fall Asleep": "fallasleep",
  "Lapdance 2": "lapdance2",
  Handshake: "handshake",
  Leanside: "leanside",
  "Idle 9": "idle9",
  "Idle 8": "idle8",
  No: "no",
  "Wait 8": "wait8",
  "Try Clothes": "tryclothes",
  "Kneel 3": "kneel3",
  "Slow Clap 3": "slowclap3",
  "No 2": "no2",
  Whistle: "whistle",
  "Sit Lean": "sitlean",
  "Fall Over 4": "fallover4",
  "Crossarms 6": "crossarms6",
  "Stretch 3": "stretch3",
  "Crossarms 4": "crossarms4",
  "Lean Bar 2": "leanbar2",
};
