let prop_emotes = {
  "Suitcase 2": "suitcase2",
  Flute: "flute",
  Wine: "wine",
  Beer: "beer",
  "Smoke 3": "smoke3",
  "Brief 3": "brief3",
  "Smoke 4": "smoke4",
  Notepad: "notepad",
  Suitcase: "suitcase",
  Coffee: "coffee",
  "Smoke 2": "smoke2",
  Joint: "joint",
  Donut: "donut",
  Clean: "clean",
  "Guitar Electric 2": "guitarelectric2",
  Cigar: "cigar",
  "Make It Rain": "makeitrain",
  Burger: "burger",
  Champagne: "champagne",
  Cig: "cig",
  "Clean 2": "clean2",
  Whiskey: "whiskey",
  Soda: "soda",
  Umbrella: "umbrella",
  Backpack: "backpack",
  "Champagne Spray": "champagnespray",
  Beg: "beg",
  Box: "box",
  Clipboard: "clipboard",
  Phone: "phone",
  "Cigar 2": "cigar2",
  Tablet: "tablet",
  Cup: "cup",
  "Tablet 2": "tablet2",
  "Phone Call": "phonecall",
  Camera: "camera",
  Map: "map",
  Bong: "bong",
  Guitar: "guitar",
  Book: "book",
  "Guitar Electric": "guitarelectric",
  "Guitar 2": "guitar2",
  Bouquet: "bouquet",
  "Ego Bar": "egobar",
  Mugshot: "mugshot",
  Rose: "rose",
  Teddy: "teddy",
  Sandwich: "sandwich",
};
