let shared_emotes = {
  "Baseball Throw": "baseballthrow",
  "Give 2": "give2",
  "Slap 2": "slap2",
  "Hug 2": "hug2",
  Bro: "bro",
  Baseball: "baseball",
  "Bro 2": "bro2",
  Slapped: "slapped",
  Hug: "hug",
  "Stickup Scared": "stickupscared",
  "Stick Up": "stickup",
  "Handshake 2": "handshake2",
  Handshake: "handshake",
  Give: "give",
  Slap: "slap",
  Headbutt: "headbutt",
  Punched: "punched",
  "Slapped 2": "slapped2",
  Headbutted: "headbutted",
  Punch: "punch",
};
